#!/usr/bin/env node

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { invokeSingle, runRoundtable, generateReactions } from './engine.js';
import type {
  PersonaConfig,
  DebateResult,
  Decision,
  InvokeResult,
} from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Persona loading
// ---------------------------------------------------------------------------

const PERSONAS_DIR = path.resolve(__dirname, '..', 'personas');

function loadPersonas(): Map<string, PersonaConfig> {
  const map = new Map<string, PersonaConfig>();
  if (!fs.existsSync(PERSONAS_DIR)) return map;

  for (const file of fs.readdirSync(PERSONAS_DIR)) {
    if (!file.endsWith('.md')) continue;
    const id = file.replace('.md', '');
    const shortName = id
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
    const name = shortName; // display name same as derived
    map.set(id, { id, name, shortName, file: path.join(PERSONAS_DIR, file) });
  }
  return map;
}

const personas = loadPersonas();

function resolvePersonas(ids: string[]): PersonaConfig[] {
  const resolved: PersonaConfig[] = [];
  for (const id of ids) {
    const p = personas.get(id);
    if (!p) throw new Error(`Unknown persona: ${id}. Available: ${[...personas.keys()].join(', ')}`);
    resolved.push(p);
  }
  return resolved;
}

// ---------------------------------------------------------------------------
// Decision log
// ---------------------------------------------------------------------------

const DECISIONS_DIR = path.resolve(__dirname, '..', 'decisions');

function logDecision(summary: string, context: string, approver: string): Decision {
  if (!fs.existsSync(DECISIONS_DIR)) fs.mkdirSync(DECISIONS_DIR, { recursive: true });

  const existing = fs.readdirSync(DECISIONS_DIR).filter((f) => f.endsWith('.json'));
  const nextNum = existing.length + 1;
  const id = `DEC-${String(nextNum).padStart(3, '0')}`;

  const decision: Decision = {
    id,
    summary,
    context,
    approver,
    timestamp: new Date().toISOString(),
  };

  fs.writeFileSync(
    path.join(DECISIONS_DIR, `${id}.json`),
    JSON.stringify(decision, null, 2),
  );
  return decision;
}

// ---------------------------------------------------------------------------
// Minutes generation
// ---------------------------------------------------------------------------

function generateMinutes(
  debate: DebateResult,
  focusAreas?: string[],
): string {
  const lines: string[] = [];
  lines.push(`# Meeting Minutes`);
  lines.push(`**Topic:** ${debate.topic}`);
  lines.push(`**Date:** ${debate.timestamp}`);
  lines.push(`**Participants:** ${debate.turns.map((t) => t.name).join(', ')}`);
  lines.push('');

  if (focusAreas?.length) {
    lines.push(`**Focus Areas:** ${focusAreas.join(', ')}`);
    lines.push('');
  }

  lines.push('## Discussion');
  lines.push('');
  for (const turn of debate.turns) {
    if (turn.passed) {
      lines.push(`- **${turn.name}:** [PASS]`);
    } else {
      lines.push(`- **${turn.name}:** ${turn.content}`);
    }
  }

  if (debate.reactions.length > 0) {
    lines.push('');
    lines.push('## Reactions');
    lines.push('');
    for (const r of debate.reactions) {
      const fromPersona = debate.turns.find((t) => t.persona === r.fromPersonaId);
      const toPersona = debate.turns[r.toTurnIndex];
      if (fromPersona && toPersona) {
        lines.push(`- ${fromPersona.name} reacted to ${toPersona.name}: **${r.type}**`);
      }
    }
  }

  lines.push('');
  lines.push('## Key Points');
  lines.push('');
  const activeTurns = debate.turns.filter((t) => !t.passed);
  for (const turn of activeTurns) {
    lines.push(`- ${turn.shortName}: ${turn.content.split('.')[0]}.`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by mcp-exec-team*');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// MCP Server
// ---------------------------------------------------------------------------

const server = new Server(
  { name: 'mcp-exec-team', version: '0.1.0' },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'invoke_debate',
      description:
        'Run a sequential roundtable debate among selected personas. Each persona sees previous responses. Returns turns, reactions, topic, and timestamp.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          persona_ids: {
            type: 'array',
            items: { type: 'string' },
            description: `Persona IDs to include. Available: ${[...personas.keys()].join(', ')}`,
          },
          question: { type: 'string', description: 'The topic or question for debate' },
          context: { type: 'string', description: 'Optional background context' },
        },
        required: ['persona_ids', 'question'],
      },
    },
    {
      name: 'get_persona',
      description: 'Get details about a specific persona including their prompt content.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          persona_id: {
            type: 'string',
            description: `Persona ID. Available: ${[...personas.keys()].join(', ')}`,
          },
        },
        required: ['persona_id'],
      },
    },
    {
      name: 'invoke_single',
      description: 'Ask a single persona a question without a roundtable.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          persona_id: { type: 'string', description: 'The persona to invoke' },
          question: { type: 'string', description: 'The question to ask' },
          context: { type: 'string', description: 'Optional background context' },
        },
        required: ['persona_id', 'question'],
      },
    },
    {
      name: 'log_decision',
      description: 'Log a decision made during or after a debate.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          summary: { type: 'string', description: 'One-line decision summary' },
          context: { type: 'string', description: 'Context or debate that led to this decision' },
          approver: { type: 'string', description: 'Who approved this decision' },
        },
        required: ['summary', 'context', 'approver'],
      },
    },
    {
      name: 'generate_minutes',
      description: 'Generate meeting minutes from a debate result.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          debate_result: {
            type: 'object',
            description: 'The DebateResult object from invoke_debate',
          },
          focus_areas: {
            type: 'array',
            items: { type: 'string' },
            description: 'Optional list of focus areas to highlight',
          },
        },
        required: ['debate_result'],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case 'invoke_debate': {
      const { persona_ids, question, context } = args as {
        persona_ids: string[];
        question: string;
        context?: string;
      };
      const selected = resolvePersonas(persona_ids);
      const turns = await runRoundtable(selected, question, context);
      const reactions = await generateReactions(selected, turns, question);
      const result: DebateResult = {
        turns,
        reactions,
        topic: question,
        timestamp: new Date().toISOString(),
      };
      return { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }] };
    }

    case 'get_persona': {
      const { persona_id } = args as { persona_id: string };
      const p = personas.get(persona_id);
      if (!p) {
        return {
          content: [
            {
              type: 'text',
              text: `Unknown persona: ${persona_id}. Available: ${[...personas.keys()].join(', ')}`,
            },
          ],
          isError: true,
        };
      }
      const prompt = fs.readFileSync(p.file, 'utf-8');
      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify({ id: p.id, name: p.name, shortName: p.shortName, prompt }, null, 2),
          },
        ],
      };
    }

    case 'invoke_single': {
      const { persona_id, question, context } = args as {
        persona_id: string;
        question: string;
        context?: string;
      };
      const selected = resolvePersonas([persona_id]);
      const result = await invokeSingle(selected[0], question, context);
      return { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }] };
    }

    case 'log_decision': {
      const { summary, context, approver } = args as {
        summary: string;
        context: string;
        approver: string;
      };
      const decision = logDecision(summary, context, approver);
      return { content: [{ type: 'text', text: JSON.stringify(decision, null, 2) }] };
    }

    case 'generate_minutes': {
      const { debate_result, focus_areas } = args as {
        debate_result: DebateResult;
        focus_areas?: string[];
      };
      const minutes = generateMinutes(debate_result, focus_areas);
      return { content: [{ type: 'text', text: minutes }] };
    }

    default:
      return {
        content: [{ type: 'text', text: `Unknown tool: ${name}` }],
        isError: true,
      };
  }
});

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('mcp-exec-team server started');
}

process.on('SIGINT', () => process.exit(0));
process.on('SIGTERM', () => process.exit(0));

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
